# pt 25
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 25 --tuneEra 201692125 --selection incl                                         --plot_directory ppv21_v3 --year 2016"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 25 --tuneEra 201692125 --selection nCleanJet1p                                  --plot_directory ppv21_v3 --year 2016"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 25 --tuneEra 201692125 --selection looseLeptonVeto-onZ                          --plot_directory ppv21_v3 --year 2016"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 25 --tuneEra 201692125 --selection looseLeptonVeto-onZ-nCleanJet1p              --plot_directory ppv21_v3 --year 2016"
#
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 25 --tuneEra 201792125 --selection incl                                         --plot_directory ppv21_v3 --year 2017"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 25 --tuneEra 201792125 --selection nCleanJet1p                                  --plot_directory ppv21_v3 --year 2017"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 25 --tuneEra 201792125 --selection nCleanJet1p-BadEEJetVeto                     --plot_directory ppv21_v3 --year 2017"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 25 --tuneEra 201792125 --selection looseLeptonVeto-onZ                          --plot_directory ppv21_v3 --year 2017"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 25 --tuneEra 201792125 --selection looseLeptonVeto-onZ-BadEEJetVeto             --plot_directory ppv21_v3 --year 2017"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 25 --tuneEra 201792125 --selection looseLeptonVeto-onZ-nCleanJet1p              --plot_directory ppv21_v3 --year 2017"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 25 --tuneEra 201792125 --selection looseLeptonVeto-onZ-nCleanJet1p-BadEEJetVeto --plot_directory ppv21_v3 --year 2017"
#
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 25 --tuneEra 201892125 --selection incl                                         --plot_directory ppv21_v3 --year 2018"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 25 --tuneEra 201892125 --selection nCleanJet1p                                  --plot_directory ppv21_v3 --year 2018"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 25 --tuneEra 201892125 --selection looseLeptonVeto-onZ                          --plot_directory ppv21_v3 --year 2018"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 25 --tuneEra 201892125 --selection looseLeptonVeto-onZ-nCleanJet1p              --plot_directory ppv21_v3 --year 2018"
#
# pt 15
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201692115 --selection incl                                         --plot_directory ppv21_v3 --year 2016"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201692115 --selection nCleanJet1p                                  --plot_directory ppv21_v3 --year 2016"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201692115 --selection looseLeptonVeto-onZ                          --plot_directory ppv21_v3 --year 2016"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201692115 --selection looseLeptonVeto-onZ-nCleanJet1p              --plot_directory ppv21_v3 --year 2016"
runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201692115 --selection looseLeptonVeto-onZ-nCleanJet0               --plot_directory ppv21_v3 --year 2016"
#
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201792115 --selection incl                                         --plot_directory ppv21_v3 --year 2017"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201792115 --selection nCleanJet1p                                  --plot_directory ppv21_v3 --year 2017"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201792115 --selection nCleanJet1p-BadEEJetVeto                     --plot_directory ppv21_v3 --year 2017"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201792115 --selection looseLeptonVeto-onZ                          --plot_directory ppv21_v3 --year 2017"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201792115 --selection looseLeptonVeto-onZ-BadEEJetVeto             --plot_directory ppv21_v3 --year 2017"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201792115 --selection looseLeptonVeto-onZ-nCleanJet1p              --plot_directory ppv21_v3 --year 2017"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201792115 --selection looseLeptonVeto-onZ-nCleanJet1p-BadEEJetVeto --plot_directory ppv21_v3 --year 2017"
runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201792115 --selection looseLeptonVeto-onZ-nCleanJet0               --plot_directory ppv21_v3 --year 2017"
runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201792115 --selection looseLeptonVeto-onZ-nCleanJet0-BadEEJetVeto  --plot_directory ppv21_v3 --year 2017"
#
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201892115 --selection incl                                         --plot_directory ppv21_v3 --year 2018"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201892115 --selection nCleanJet1p                                  --plot_directory ppv21_v3 --year 2018"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201892115 --selection looseLeptonVeto-onZ                          --plot_directory ppv21_v3 --year 2018"
#runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201892115 --selection looseLeptonVeto-onZ-nCleanJet1p              --plot_directory ppv21_v3 --year 2018"
runNotifier.sh "python analysisPlots.py --calcMETSig --jetThreshold 15 --tuneEra 201892115 --selection looseLeptonVeto-onZ-nCleanJet0               --plot_directory ppv21_v3 --year 2018"
